version: '3'
networks:
  healthnet:
services:
    provider1:
        build:
            context: ./
            dockerfile: Containerfile
        ports:
            - '30333:30333'
            - '9944:9944'
            - '9933:9933'
        container_name: provider1
        networks:
          - healthnet
        entrypoint: 
          - /usr/bin/entrypoint.sh
          - alice

    provider2:
        build:
            context: ./
            dockerfile: Containerfile
        ports:
            - '30334:30334'
            - '9946:9946'
            - '9934:9934'
        container_name: provider2
        networks:
          - healthnet
        entrypoint: 
          - /usr/bin/entrypoint.sh
          - bob
        working_dir: /home/polkadot

    maintainer:
      build:
          context: ./
          dockerfile: Containerfile
      ports:
          - '30335:30335'
          - '9947:9947'
          - '9935:9935'
      container_name: maintainer
      networks:
        - healthnet
      entrypoint: 
        - /usr/bin/entrypoint.sh
        - charlie
      working_dir: /home/polkadot
    

   